/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBasicFamilyScopeProvider extends DelegatingScopeProvider {
}
