/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.scoping;

import org.xtext.example.basicfamily.scoping.AbstractBasicFamilyScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BasicFamilyScopeProvider extends AbstractBasicFamilyScopeProvider {
}
