/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BasicFamilyStandaloneSetup extends BasicFamilyStandaloneSetupGenerated {

	def static void doSetup() {
		new BasicFamilyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
