/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.validation;

import org.xtext.example.basicfamily.validation.AbstractBasicFamilyValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BasicFamilyValidator extends AbstractBasicFamilyValidator {
}
