/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BasicFamilyGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FamilyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.basicfamily.BasicFamily.Family");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFamilyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFamilyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMembersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cMembersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cMembersPersonParserRuleCall_4_2_0 = (RuleCall)cMembersAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cMembersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cMembersPersonParserRuleCall_4_3_1_0 = (RuleCall)cMembersAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Family:
		//	{Family}
		//	'Family'
		//	name=EString
		//	'{' ('members' '{' members+=Person ("," members+=Person)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Family} 'Family' name=EString '{' ('members' '{' members+=Person ("," members+=Person)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Family}
		public Action getFamilyAction_0() { return cFamilyAction_0; }
		
		//'Family'
		public Keyword getFamilyKeyword_1() { return cFamilyKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('members' '{' members+=Person ("," members+=Person)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'members'
		public Keyword getMembersKeyword_4_0() { return cMembersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//members+=Person
		public Assignment getMembersAssignment_4_2() { return cMembersAssignment_4_2; }
		
		//Person
		public RuleCall getMembersPersonParserRuleCall_4_2_0() { return cMembersPersonParserRuleCall_4_2_0; }
		
		//("," members+=Person)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//members+=Person
		public Assignment getMembersAssignment_4_3_1() { return cMembersAssignment_4_3_1; }
		
		//Person
		public RuleCall getMembersPersonParserRuleCall_4_3_1_0() { return cMembersPersonParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.basicfamily.BasicFamily.Person");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cManParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWomanParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Person:
		//	Man | Woman;
		@Override public ParserRule getRule() { return rule; }
		
		//Man | Woman
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Man
		public RuleCall getManParserRuleCall_0() { return cManParserRuleCall_0; }
		
		//Woman
		public RuleCall getWomanParserRuleCall_1() { return cWomanParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.basicfamily.BasicFamily.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class WomanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.basicfamily.BasicFamily.Woman");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWomanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWomanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParentsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParentsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cParentsPersonCrossReference_4_2_0 = (CrossReference)cParentsAssignment_4_2.eContents().get(0);
		private final RuleCall cParentsPersonEStringParserRuleCall_4_2_0_1 = (RuleCall)cParentsPersonCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParentsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cParentsPersonCrossReference_4_3_1_0 = (CrossReference)cParentsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cParentsPersonEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cParentsPersonCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChildrenKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cChildrenAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cChildrenPersonCrossReference_5_2_0 = (CrossReference)cChildrenAssignment_5_2.eContents().get(0);
		private final RuleCall cChildrenPersonEStringParserRuleCall_5_2_0_1 = (RuleCall)cChildrenPersonCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cChildrenAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cChildrenPersonCrossReference_5_3_1_0 = (CrossReference)cChildrenAssignment_5_3_1.eContents().get(0);
		private final RuleCall cChildrenPersonEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cChildrenPersonCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMotherKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMotherAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cMotherWomanCrossReference_6_1_0 = (CrossReference)cMotherAssignment_6_1.eContents().get(0);
		private final RuleCall cMotherWomanEStringParserRuleCall_6_1_0_1 = (RuleCall)cMotherWomanCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFatherKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFatherAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cFatherManCrossReference_7_1_0 = (CrossReference)cFatherAssignment_7_1.eContents().get(0);
		private final RuleCall cFatherManEStringParserRuleCall_7_1_0_1 = (RuleCall)cFatherManCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Woman:
		//	{Woman}
		//	'Woman'
		//	name=EString
		//	'{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')? ('children' '('
		//	children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])? ('father'
		//	father=[Man|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Woman} 'Woman' name=EString '{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')?
		//('children' '(' children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])?
		//('father' father=[Man|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Woman}
		public Action getWomanAction_0() { return cWomanAction_0; }
		
		//'Woman'
		public Keyword getWomanKeyword_1() { return cWomanKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parents'
		public Keyword getParentsKeyword_4_0() { return cParentsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//parents+=[Person|EString]
		public Assignment getParentsAssignment_4_2() { return cParentsAssignment_4_2; }
		
		//[Person|EString]
		public CrossReference getParentsPersonCrossReference_4_2_0() { return cParentsPersonCrossReference_4_2_0; }
		
		//EString
		public RuleCall getParentsPersonEStringParserRuleCall_4_2_0_1() { return cParentsPersonEStringParserRuleCall_4_2_0_1; }
		
		//("," parents+=[Person|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parents+=[Person|EString]
		public Assignment getParentsAssignment_4_3_1() { return cParentsAssignment_4_3_1; }
		
		//[Person|EString]
		public CrossReference getParentsPersonCrossReference_4_3_1_0() { return cParentsPersonCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getParentsPersonEStringParserRuleCall_4_3_1_0_1() { return cParentsPersonEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('children' '(' children+=[Person|EString] ("," children+=[Person|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'children'
		public Keyword getChildrenKeyword_5_0() { return cChildrenKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//children+=[Person|EString]
		public Assignment getChildrenAssignment_5_2() { return cChildrenAssignment_5_2; }
		
		//[Person|EString]
		public CrossReference getChildrenPersonCrossReference_5_2_0() { return cChildrenPersonCrossReference_5_2_0; }
		
		//EString
		public RuleCall getChildrenPersonEStringParserRuleCall_5_2_0_1() { return cChildrenPersonEStringParserRuleCall_5_2_0_1; }
		
		//("," children+=[Person|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//children+=[Person|EString]
		public Assignment getChildrenAssignment_5_3_1() { return cChildrenAssignment_5_3_1; }
		
		//[Person|EString]
		public CrossReference getChildrenPersonCrossReference_5_3_1_0() { return cChildrenPersonCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getChildrenPersonEStringParserRuleCall_5_3_1_0_1() { return cChildrenPersonEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('mother' mother=[Woman|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'mother'
		public Keyword getMotherKeyword_6_0() { return cMotherKeyword_6_0; }
		
		//mother=[Woman|EString]
		public Assignment getMotherAssignment_6_1() { return cMotherAssignment_6_1; }
		
		//[Woman|EString]
		public CrossReference getMotherWomanCrossReference_6_1_0() { return cMotherWomanCrossReference_6_1_0; }
		
		//EString
		public RuleCall getMotherWomanEStringParserRuleCall_6_1_0_1() { return cMotherWomanEStringParserRuleCall_6_1_0_1; }
		
		//('father' father=[Man|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'father'
		public Keyword getFatherKeyword_7_0() { return cFatherKeyword_7_0; }
		
		//father=[Man|EString]
		public Assignment getFatherAssignment_7_1() { return cFatherAssignment_7_1; }
		
		//[Man|EString]
		public CrossReference getFatherManCrossReference_7_1_0() { return cFatherManCrossReference_7_1_0; }
		
		//EString
		public RuleCall getFatherManEStringParserRuleCall_7_1_0_1() { return cFatherManEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ManElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.basicfamily.BasicFamily.Man");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cManAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cManKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParentsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParentsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cParentsPersonCrossReference_4_2_0 = (CrossReference)cParentsAssignment_4_2.eContents().get(0);
		private final RuleCall cParentsPersonEStringParserRuleCall_4_2_0_1 = (RuleCall)cParentsPersonCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParentsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cParentsPersonCrossReference_4_3_1_0 = (CrossReference)cParentsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cParentsPersonEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cParentsPersonCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChildrenKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cChildrenAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cChildrenPersonCrossReference_5_2_0 = (CrossReference)cChildrenAssignment_5_2.eContents().get(0);
		private final RuleCall cChildrenPersonEStringParserRuleCall_5_2_0_1 = (RuleCall)cChildrenPersonCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cChildrenAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cChildrenPersonCrossReference_5_3_1_0 = (CrossReference)cChildrenAssignment_5_3_1.eContents().get(0);
		private final RuleCall cChildrenPersonEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cChildrenPersonCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cMotherKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cMotherAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cMotherWomanCrossReference_6_1_0 = (CrossReference)cMotherAssignment_6_1.eContents().get(0);
		private final RuleCall cMotherWomanEStringParserRuleCall_6_1_0_1 = (RuleCall)cMotherWomanCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cFatherKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFatherAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cFatherManCrossReference_7_1_0 = (CrossReference)cFatherAssignment_7_1.eContents().get(0);
		private final RuleCall cFatherManEStringParserRuleCall_7_1_0_1 = (RuleCall)cFatherManCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Man:
		//	{Man}
		//	'Man'
		//	name=EString
		//	'{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')? ('children' '('
		//	children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])? ('father'
		//	father=[Man|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Man} 'Man' name=EString '{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')? ('children'
		//'(' children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])? ('father'
		//father=[Man|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Man}
		public Action getManAction_0() { return cManAction_0; }
		
		//'Man'
		public Keyword getManKeyword_1() { return cManKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parents'
		public Keyword getParentsKeyword_4_0() { return cParentsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//parents+=[Person|EString]
		public Assignment getParentsAssignment_4_2() { return cParentsAssignment_4_2; }
		
		//[Person|EString]
		public CrossReference getParentsPersonCrossReference_4_2_0() { return cParentsPersonCrossReference_4_2_0; }
		
		//EString
		public RuleCall getParentsPersonEStringParserRuleCall_4_2_0_1() { return cParentsPersonEStringParserRuleCall_4_2_0_1; }
		
		//("," parents+=[Person|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parents+=[Person|EString]
		public Assignment getParentsAssignment_4_3_1() { return cParentsAssignment_4_3_1; }
		
		//[Person|EString]
		public CrossReference getParentsPersonCrossReference_4_3_1_0() { return cParentsPersonCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getParentsPersonEStringParserRuleCall_4_3_1_0_1() { return cParentsPersonEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('children' '(' children+=[Person|EString] ("," children+=[Person|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'children'
		public Keyword getChildrenKeyword_5_0() { return cChildrenKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//children+=[Person|EString]
		public Assignment getChildrenAssignment_5_2() { return cChildrenAssignment_5_2; }
		
		//[Person|EString]
		public CrossReference getChildrenPersonCrossReference_5_2_0() { return cChildrenPersonCrossReference_5_2_0; }
		
		//EString
		public RuleCall getChildrenPersonEStringParserRuleCall_5_2_0_1() { return cChildrenPersonEStringParserRuleCall_5_2_0_1; }
		
		//("," children+=[Person|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//children+=[Person|EString]
		public Assignment getChildrenAssignment_5_3_1() { return cChildrenAssignment_5_3_1; }
		
		//[Person|EString]
		public CrossReference getChildrenPersonCrossReference_5_3_1_0() { return cChildrenPersonCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getChildrenPersonEStringParserRuleCall_5_3_1_0_1() { return cChildrenPersonEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('mother' mother=[Woman|EString])?
		public Group getGroup_6() { return cGroup_6; }
		
		//'mother'
		public Keyword getMotherKeyword_6_0() { return cMotherKeyword_6_0; }
		
		//mother=[Woman|EString]
		public Assignment getMotherAssignment_6_1() { return cMotherAssignment_6_1; }
		
		//[Woman|EString]
		public CrossReference getMotherWomanCrossReference_6_1_0() { return cMotherWomanCrossReference_6_1_0; }
		
		//EString
		public RuleCall getMotherWomanEStringParserRuleCall_6_1_0_1() { return cMotherWomanEStringParserRuleCall_6_1_0_1; }
		
		//('father' father=[Man|EString])?
		public Group getGroup_7() { return cGroup_7; }
		
		//'father'
		public Keyword getFatherKeyword_7_0() { return cFatherKeyword_7_0; }
		
		//father=[Man|EString]
		public Assignment getFatherAssignment_7_1() { return cFatherAssignment_7_1; }
		
		//[Man|EString]
		public CrossReference getFatherManCrossReference_7_1_0() { return cFatherManCrossReference_7_1_0; }
		
		//EString
		public RuleCall getFatherManEStringParserRuleCall_7_1_0_1() { return cFatherManEStringParserRuleCall_7_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final FamilyElements pFamily;
	private final PersonElements pPerson;
	private final EStringElements pEString;
	private final WomanElements pWoman;
	private final ManElements pMan;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BasicFamilyGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFamily = new FamilyElements();
		this.pPerson = new PersonElements();
		this.pEString = new EStringElements();
		this.pWoman = new WomanElements();
		this.pMan = new ManElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.basicfamily.BasicFamily".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Family:
	//	{Family}
	//	'Family'
	//	name=EString
	//	'{' ('members' '{' members+=Person ("," members+=Person)* '}')?
	//	'}';
	public FamilyElements getFamilyAccess() {
		return pFamily;
	}
	
	public ParserRule getFamilyRule() {
		return getFamilyAccess().getRule();
	}
	
	//Person:
	//	Man | Woman;
	public PersonElements getPersonAccess() {
		return pPerson;
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Woman:
	//	{Woman}
	//	'Woman'
	//	name=EString
	//	'{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')? ('children' '('
	//	children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])? ('father'
	//	father=[Man|EString])?
	//	'}';
	public WomanElements getWomanAccess() {
		return pWoman;
	}
	
	public ParserRule getWomanRule() {
		return getWomanAccess().getRule();
	}
	
	//Man:
	//	{Man}
	//	'Man'
	//	name=EString
	//	'{' ('parents' '(' parents+=[Person|EString] ("," parents+=[Person|EString])* ')')? ('children' '('
	//	children+=[Person|EString] ("," children+=[Person|EString])* ')')? ('mother' mother=[Woman|EString])? ('father'
	//	father=[Man|EString])?
	//	'}';
	public ManElements getManAccess() {
		return pMan;
	}
	
	public ParserRule getManRule() {
		return getManAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
