/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily;

import org.xtext.example.basicfamily.AbstractBasicFamilyRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BasicFamilyRuntimeModule extends AbstractBasicFamilyRuntimeModule {
}
