/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.basicfamily.ui.AbstractBasicFamilyUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BasicFamilyUiModule extends AbstractBasicFamilyUiModule {
  public BasicFamilyUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
