/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.basicfamily.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.basicfamily.parser.antlr.internal.InternalBasicFamilyParser;
import org.xtext.example.basicfamily.services.BasicFamilyGrammarAccess;

public class BasicFamilyParser extends AbstractAntlrParser {

	@Inject
	private BasicFamilyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBasicFamilyParser createParser(XtextTokenStream stream) {
		return new InternalBasicFamilyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Family";
	}

	public BasicFamilyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BasicFamilyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
